### ISSUE TITLE
Not working in 1.8.9

### ISSUE THREAD

**Issue by AJAJPJuan** [Verclene/EBLib#1]
In the mod description and name says it is for 1.8.X, but when installed in a Forge 1.8.9 the mod calls for Forge 1.8, and so not initializating correctly.

**Comment by Verclene** [comment]
Use EBLib 3 Build 10(3.1.10). I checked on Forge 11.15.0.1715 and it works.
Released **LMMNX** does still not work on 1.8.9.

**Comment by AJAJPJuan** [comment]
Oops, wrong place. Sorry! Thanks for your attention.
